In [1]:
import os
import pandas as pd
import numpy as np
import sklearn
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt

In [2]:
df = pd.DataFrame({'A': [1,2], 'B': [3,4]})
print(df)

   A  B
0  1  3
1  2  4


In [3]:
df.shape

(2, 2)

In [4]:
df.shape[0]*df.shape[1]

4

In [5]:
row, col = df.shape
print(row, col)

2 2


In [6]:
path = r'C:\Users\noahh\Documents\JN_EX\4310\data\train.csv'
df = pd.read_csv(path)
print(df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [9]:
print(len(df.columns))

12


In [10]:
print(df.shape)

(891, 12)


In [11]:
print(df.shape[0]*df.shape[1])

10692


In [12]:
print(df.size)

10692


In [13]:
df_multiindex = df.set_index(['Sex', 'Pclass', 'Embarked', 'PassengerId'])

In [14]:
print(len(df_multiindex.columns))

8


In [15]:
df_multiindex.columns

Index(['Survived', 'Name', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin'], dtype='object')

In [16]:
df_multiindex.index

MultiIndex([(  'male', 3, 'S',   1),
            ('female', 1, 'C',   2),
            ('female', 3, 'S',   3),
            ('female', 1, 'S',   4),
            (  'male', 3, 'S',   5),
            (  'male', 3, 'Q',   6),
            (  'male', 1, 'S',   7),
            (  'male', 3, 'S',   8),
            ('female', 3, 'S',   9),
            ('female', 2, 'C',  10),
            ...
            (  'male', 3, 'S', 882),
            ('female', 3, 'S', 883),
            (  'male', 2, 'S', 884),
            (  'male', 3, 'S', 885),
            ('female', 3, 'Q', 886),
            (  'male', 2, 'S', 887),
            ('female', 1, 'S', 888),
            ('female', 3, 'S', 889),
            (  'male', 1, 'C', 890),
            (  'male', 3, 'Q', 891)],
           names=['Sex', 'Pclass', 'Embarked', 'PassengerId'], length=891)

In [17]:
print(df_multiindex.shape)

(891, 8)


In [18]:
print(df_multiindex.size)

7128


In [19]:
df_multiindex

Survived  \
Sex    Pclass Embarked PassengerId             
male   3      S        1                   0   
female 1      C        2                   1   
       3      S        3                   1   
       1      S        4                   1   
male   3      S        5                   0   
...                                      ...   
       2      S        887                 0   
female 1      S        888                 1   
       3      S        889                 0   
male   1      C        890                 1   
       3      Q        891                 0   

                                                                                 Name  \
Sex    Pclass Embarked PassengerId                                                      
male   3      S        1                                      Braund, Mr. Owen Harris   
female 1      C        2            Cumings, Mrs. John Bradley (Florence Briggs Th...   
       3      S        3                                       Heikkinen, Miss. Laina   
       1      S        4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)   
male   3      S        5                                     Allen, Mr. William Henry   
...                                                                               ...   
       2      S        887                                      Montvila, Rev. Juozas   
female 1      S        888                               Graham, Miss. Margaret Edith   
       3      S        889                   Johnston, Miss. Catherine Helen "Carrie"   
male   1      C        890                                      Behr, Mr. Karl Howell   
       3      Q        891                                        Dooley, Mr. Patrick   

                                     Age  SibSp  Parch            Ticket  \
Sex    Pclass Embarked PassengerId                                         
male   3      S        1            22.0      1      0         A/5 21171   
female 1      C        2            38.0      1      0          PC 17599   
       3      S        3            26.0      0      0  STON/O2. 3101282   
       1      S        4            35.0      1      0            113803   
male   3      S        5            35.0      0      0            373450   
...                                  ...    ...    ...               ...   
       2      S        887          27.0      0      0            211536   
female 1      S        888          19.0      0      0            112053   
       3      S        889           NaN      1      2        W./C. 6607   
male   1      C        890          26.0      0      0            111369   
       3      Q        891          32.0      0      0            370376   

                                       Fare Cabin  
Sex    Pclass Embarked PassengerId                 
male   3      S        1             7.2500   NaN  
female 1      C        2            71.2833   C85  
       3      S        3             7.9250   NaN  
       1      S        4            53.1000  C123  
male   3      S        5             8.0500   NaN  
...                                     ...   ...  
       2      S        887          13.0000   NaN  
female 1      S        888          30.0000   B42  
       3      S        889          23.4500   NaN  
male   1      C        890          30.0000  C148  
       3      Q        891           7.7500   NaN  

[891 rows x 8 columns]

In [20]:
s = df['PassengerId']
print(s.head())

0    1
1    2
2    3
3    4
4    5
Name: PassengerId, dtype: int64


In [21]:
print(len(s))

891


In [22]:
print(s.size)

891


In [23]:
print(s.shape)

(891,)


In [24]:
df = pd.DataFrame({'A': [1,2,3]})
print(df)

   A
0  1
1  2
2  3


In [29]:
type(df)

pandas.core.frame.DataFrame

In [30]:
data = {'a': 1, 'b': 2, 'c': 3, 'd' : 4, 'e' : 5}
s = pd.Series(data)
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [31]:
A = ['0', '1', '1', '0']
B = ['1', '0', '1', '0']
C = ['0', '1', '0', '1']
D = ['1', '0', '0', '1']
E = ['1', '1', '0', '0']
X = pd.DataFrame({"A": A, "B":B, "C":C,"D":D})
y = pd.DataFrame({"E":E})
print("X=\n", X)
print("y:\n", y)
X = X.to_numpy()
y = y.to_numpy()
print("\nX=\n", X)
print("\ny:\n", y)
print("\nshape of X:\n", X.shape)
print("\nshape of y:\n", y.shape)
print("\ny[0]=\n",y[0])
y = y.astype(np.uint8)
print("\ny:\n", y)

X=
    A  B  C  D
0  0  1  0  1
1  1  0  1  0
2  1  1  0  0
3  0  0  1  1
y:
    E
0  1
1  1
2  0
3  0

X=
 [['0' '1' '0' '1']
 ['1' '0' '1' '0']
 ['1' '1' '0' '0']
 ['0' '0' '1' '1']]

y:
 [['1']
 ['1']
 ['0']
 ['0']]

shape of X:
 (4, 4)

shape of y:
 (4, 1)

y[0]=
 ['1']

y:
 [[1]
 [1]
 [0]
 [0]]


In [33]:
def my_function(**names):
    print(names["name2"])
    
my_function(name1 = "Rachel", name2 = "John", name3 = "Grace")

John


In [34]:
A = [1,2,3,4,0]
B = [5,6,7,8,0]
C = [9,10,11,12,0]
D = [13,14,15,16,0]
df = pd.DataFrame({"A":A, "B": B, "C": C, "D":D})
print("df:\n", df)
X = df.to_numpy()
instances = X[:5]
print("\nnp array:\n", instances)
type(instances)

df:
    A  B   C   D
0  1  5   9  13
1  2  6  10  14
2  3  7  11  15
3  4  8  12  16
4  0  0   0   0

np array:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]
 [ 0  0  0  0]]


numpy.ndarray

In [35]:
X[0]

array([ 1,  5,  9, 13], dtype=int64)

In [36]:
X[:2]

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14]], dtype=int64)

In [37]:
X

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16],
       [ 0,  0,  0,  0]], dtype=int64)

In [38]:
X_E_5 = (X == 5)
X_GTE_5 = (X >= 5)
X_ODD = (X%2==1)
print("\nX_E_5:\n", X_E_5)
print("\nX_GTE_5:\n", X_GTE_5)
print("\nX_ODD:\n", X_ODD)


X_E_5:
 [[False  True False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]

X_GTE_5:
 [[False  True  True  True]
 [False  True  True  True]
 [False  True  True  True]
 [False  True  True  True]
 [False False False False]]

X_ODD:
 [[ True  True  True  True]
 [False False False False]
 [ True  True  True  True]
 [False False False False]
 [False False False False]]
